商品説明送料自動入力
//パター
javascript: (function() {document.querySelectorAll('textarea[name="body"]').item(0).value = "shaft: \nlength: \n\nHead cover include　又は　Head cover NOT include \n\nExtra shipping fee $6 applied for rural area\n\nthanks";

document.querySelectorAll('select#pickup').item(0).selectedIndex=0;document.querySelectorAll('input#gh_2').item(0).checked = true;setShippingOption(4);for(var i=0;i < 4;i++) {addAnotherDeliveryMethod(this)} document.querySelectorAll('input#delivery_cost_1').item(0).value = "10";document.querySelectorAll('input#delivery_cost_2').item(0).value = "15";document.querySelectorAll('input#delivery_cost_3').item(0).value = "20";document.querySelectorAll('input#delivery_cost_4').item(0).value = "16";document.querySelectorAll('input#delivery_cost_5').item(0).value = "21";document.querySelectorAll('input#delivery_cost_6').item(0).value = "26";document.querySelectorAll('input#delivery_method_1').item(0).value = "within Auckland";document.querySelectorAll('input#delivery_method_2').item(0).value = "within North Island";document.querySelectorAll('input#delivery_method_3').item(0).value = "within South Island";document.querySelectorAll('input#delivery_method_4').item(0).value = "within Auckland rural area";document.querySelectorAll('input#delivery_method_5').item(0).value = "within North Island rural area";document.querySelectorAll('input#delivery_method_6').item(0).value = "within South Island rural area";})();

-----------
//アイアンセット
javascript: (function() {document.querySelectorAll('textarea[name="body"]').item(0).value = "shaft: \nflex: \n6set(5～9,P) \n\nExtra shipping fee $6 applied for rural area\n\nThanks";

document.querySelectorAll('select#pickup').item(0).selectedIndex= 0;document.querySelectorAll('input#gh_2').item(0).checked = true;setShippingOption(4);for(var i=0;i < 4;i++) {addAnotherDeliveryMethod(this)} document.querySelectorAll('input#delivery_cost_1').item(0).value = "10";document.querySelectorAll('input#delivery_cost_2').item(0).value = "15";document.querySelectorAll('input#delivery_cost_3').item(0).value = "20";document.querySelectorAll('input#delivery_cost_4').item(0).value = "16";document.querySelectorAll('input#delivery_cost_5').item(0).value = "21";document.querySelectorAll('input#delivery_cost_6').item(0).value = "26";document.querySelectorAll('input#delivery_method_1').item(0).value = "within Auckland";document.querySelectorAll('input#delivery_method_2').item(0).value = "within North Island";document.querySelectorAll('input#delivery_method_3').item(0).value = "within South Island";document.querySelectorAll('input#delivery_method_4').item(0).value = "within Auckland rural area";document.querySelectorAll('input#delivery_method_5').item(0).value = "within North Island rural area";document.querySelectorAll('input#delivery_method_6').item(0).value = "within South Island rural area";})();

-----------
○ドライバー、ウッド、UT
javascript: (function() {document.querySelectorAll('textarea[name="body"]').item(0).value = "shaft: \nflex: \nloft: °\n\nHead cover included 　又は　Head cover NOT included\n\nExtra shipping fee $6 applied for rural area\n\nThanks";

document.querySelectorAll('select#pickup').item(0).selectedIndex= 0;document.querySelectorAll('input#gh_2').item(0).checked = true;setShippingOption(4);for(var i=0;i < 4;i++) {addAnotherDeliveryMethod(this)} document.querySelectorAll('input#delivery_cost_1').item(0).value = "10";document.querySelectorAll('input#delivery_cost_2').item(0).value = "15";document.querySelectorAll('input#delivery_cost_3').item(0).value = "20";document.querySelectorAll('input#delivery_cost_4').item(0).value = "16";document.querySelectorAll('input#delivery_cost_5').item(0).value = "21";document.querySelectorAll('input#delivery_cost_6').item(0).value = "26";document.querySelectorAll('input#delivery_method_1').item(0).value = "within Auckland";document.querySelectorAll('input#delivery_method_2').item(0).value = "within North Island";document.querySelectorAll('input#delivery_method_3').item(0).value = "within South Island";document.querySelectorAll('input#delivery_method_4').item(0).value = "within Auckland rural area";document.querySelectorAll('input#delivery_method_5').item(0).value = "within North Island rural area";document.querySelectorAll('input#delivery_method_6').item(0).value = "within South Island rural area";})();

-----------
○ウェッジ
javascript: (function() {document.querySelectorAll('textarea[name="body"]').item(0).value = "shaft: \nloft: °\n\nExtra shipping fee $6 applied for rural area\n\nThanks";

document.querySelectorAll('select#pickup').item(0).selectedIndex= 0;document.querySelectorAll('input#gh_2').item(0).checked = true;setShippingOption(4);for(var i=0;i < 4;i++) {addAnotherDeliveryMethod(this)} document.querySelectorAll('input#delivery_cost_1').item(0).value = "10";document.querySelectorAll('input#delivery_cost_2').item(0).value = "15";document.querySelectorAll('input#delivery_cost_3').item(0).value = "20";document.querySelectorAll('input#delivery_cost_4').item(0).value = "16";document.querySelectorAll('input#delivery_cost_5').item(0).value = "21";document.querySelectorAll('input#delivery_cost_6').item(0).value = "26";document.querySelectorAll('input#delivery_method_1').item(0).value = "within Auckland";document.querySelectorAll('input#delivery_method_2').item(0).value = "within North Island";document.querySelectorAll('input#delivery_method_3').item(0).value = "within South Island";document.querySelectorAll('input#delivery_method_4').item(0).value = "within Auckland rural area";document.querySelectorAll('input#delivery_method_5').item(0).value = "within North Island rural area";document.querySelectorAll('input#delivery_method_6').item(0).value = "within South Island rural area";})();

-----------
○バッグ
javascript: (function() {document.querySelectorAll('textarea[name="body"]').item(0).value = "*BRAND NEW*\n名前\n\nModel:\nColour:\n\nExtra shipping fee $6 applied for rural area\n\nThanks\n\n\n\n*バッグを上から撮った写真必須";

document.querySelectorAll('select#pickup').item(0).selectedIndex= 0;document.querySelectorAll('input#gh_2').item(0).checked = true;setShippingOption(4);for(var i=0;i < 4;i++) {addAnotherDeliveryMethod(this)} document.querySelectorAll('input#delivery_cost_1').item(0).value = "15";document.querySelectorAll('input#delivery_cost_2').item(0).value = "20";document.querySelectorAll('input#delivery_cost_3').item(0).value = "25";document.querySelectorAll('input#delivery_cost_4').item(0).value = "21";document.querySelectorAll('input#delivery_cost_5').item(0).value = "26";document.querySelectorAll('input#delivery_cost_6').item(0).value = "31";document.querySelectorAll('input#delivery_method_1').item(0).value = "within Auckland";document.querySelectorAll('input#delivery_method_2').item(0).value = "within North Island";document.querySelectorAll('input#delivery_method_3').item(0).value = "within South Island";document.querySelectorAll('input#delivery_method_4').item(0).value = "within Auckland rural area";document.querySelectorAll('input#delivery_method_5').item(0).value = "within North Island rural area";document.querySelectorAll('input#delivery_method_6').item(0).value = "within South Island rural area";})();

送料自動入力(カート)
-----------
javascript: (function() {document.querySelectorAll('select#pickup').item(0).selectedIndex= 0;document.querySelectorAll('input#gh_2').item(0).checked = true;setShippingOption(4);for(var i=0;i < 4;i++) {addAnotherDeliveryMethod(this)} document.querySelectorAll('input#delivery_cost_1').item(0).value = "15";document.querySelectorAll('input#delivery_cost_2').item(0).value = "25";document.querySelectorAll('input#delivery_cost_3').item(0).value = "35";document.querySelectorAll('input#delivery_cost_4').item(0).value = "21";document.querySelectorAll('input#delivery_cost_5').item(0).value = "31";document.querySelectorAll('input#delivery_cost_6').item(0).value = "41";document.querySelectorAll('input#delivery_method_1').item(0).value = "within Auckland";document.querySelectorAll('input#delivery_method_2').item(0).value = "within North Island";document.querySelectorAll('input#delivery_method_3').item(0).value = "within South Island";document.querySelectorAll('input#delivery_method_4').item(0).value = "within Auckland rural area";document.querySelectorAll('input#delivery_method_5').item(0).value = "within North Island rural area";document.querySelectorAll('input#delivery_method_6').item(0).value = "within South Island rural area";})();

送料自動入力(小物小 ティー等)
-----------
javascript: (function() {document.querySelectorAll('select#pickup').item(0).selectedIndex= 0;document.querySelectorAll('input#gh_2').item(0).checked = true;setShippingOption(4);document.querySelectorAll('input#delivery_cost_1').item(0).value = "3";document.querySelectorAll('input#delivery_method_1').item(0).value = "Postage";})();


送料自動入力(小物大 ヘッドカバー等)
-----------
javascript: (function() {document.querySelectorAll('select#pickup').item(0).selectedIndex= 0;document.querySelectorAll('input#gh_2').item(0).checked = true;setShippingOption(4);document.querySelectorAll('input#delivery_cost_1').item(0).value = "5";document.querySelectorAll('input#delivery_method_1').item(0).value = "Postage";})();
